# Generated by Django 4.1.5 on 2023-02-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_Name', models.CharField(max_length=100, null=True)),
                ('owner_pic', models.ImageField(blank=True, null=True, upload_to='Housepic')),
                ('house_address', models.TextField()),
                ('building_img1', models.ImageField(blank=True, null=True, upload_to='Housepic')),
                ('boom_img1', models.ImageField(blank=True, null=True, upload_to='Housepic')),
                ('room_img2', models.ImageField(blank=True, null=True, upload_to='Housepic')),
                ('room_img3', models.ImageField(blank=True, null=True, upload_to='Housepic')),
                ('landmark', models.TextField()),
                ('house_type', models.CharField(default='2BD/3BD/1BD/ROOMANDPALOOR/ROOMSELF', max_length=100)),
                ('house_description', models.TextField(default='Write something About how good and what are the facilities your renters will get there like electricity/Water etc')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('phone_no', models.IntegerField()),
                ('Price', models.IntegerField(default=1000)),
                ('available', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='tenant_picture')),
                ('family_size', models.CharField(choices=[('SINGLE', 'single'), ('MARRIED', 'FAMILY OF ONE'), ('MARRIED', 'FAMILY OF TWO'), ('MARRIED', 'FAMILY OF THREE'), ('MARRIED', 'FAMILY OF FOUR'), ('MARRIED', 'FAMILY OF FIVE'), ('MARRIED', 'FAMILY OF SIX')], default='single', max_length=200)),
                ('phone_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('landlord_name', models.CharField(blank=True, max_length=100, null=True)),
                ('landlords_phone_no', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
