# Generated by Django 4.1.5 on 2023-02-04 13:02

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_landlord_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='landlords_phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
