# Generated by Django 4.1.5 on 2023-02-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_landlord_app', '0002_alter_tenant_landlords_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='house_address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='landmark',
            field=models.CharField(max_length=200),
        ),
    ]
